version: '3.8'

services:
  backend:
    build: .
    ports:
      - "12345:12345"
    volumes:
      - ./src:/app/src

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public/index.html:/usr/share/nginx/html/index.html
      - ./public/game.js:/usr/share/nginx/html/game.js
    depends_on:
      - backend